In [1]:
import torch 
print(torch.__version__)

2.5.1+cu121


In [2]:
if torch.cuda.is_available():
    print("GPU is available")
    print(torch.cuda.get_device_name(0))
else:
    print("not gpu")

GPU is available
NVIDIA GeForce RTX 3050 Ti Laptop GPU


In [3]:
a = torch.empty(2,3)

In [4]:
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [5]:
torch.rand(2,3)

tensor([[0.5791, 0.2884, 0.1955],
        [0.6526, 0.0255, 0.0470]])

In [6]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [7]:
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [8]:
x = torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [9]:
x.shape

torch.Size([2, 3])

In [10]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [11]:
torch.rand_like(x, dtype=torch.float32)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

In [12]:
# assign data type
torch.tensor([1.0,2.0,3.0], dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [13]:
# using to()
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

## Mathematical operations
# 1. Scalar operation

In [14]:
x = torch.rand(2,2)
x

tensor([[0.7118, 0.7876],
        [0.4183, 0.9014]])

In [15]:
a = torch.rand(2,3)
b = torch.rand(2,3)

In [16]:
# add
a + b
# sub
a - b
# multiply
a * b
# division
a / b
# power
a ** b
# mod
a % b

tensor([[0.4411, 0.7565, 0.2239],
        [0.3023, 0.1784, 0.3346]])

In [17]:
c = torch.tensor([1, -2, 3, -4])

In [18]:
# abs
torch.abs(c)

tensor([1, 2, 3, 4])

In [19]:
# negative
torch.neg(c)

tensor([-1,  2, -3,  4])

In [20]:
# round
d = torch.tensor([1.9, 2.3, 3.7, 4.4])
torch.round(d)

tensor([2., 2., 4., 4.])

In [21]:
# clamp
torch.clamp(d, min=2, max=3)

tensor([2.0000, 2.3000, 3.0000, 3.0000])

In [22]:
e = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
e

tensor([[8., 0., 7.],
        [0., 0., 9.]])

In [23]:
# sum
torch.sum(e)
# sum along columns
torch.sum(e, dim=0)
# sum along rows
torch.sum(e, dim=1)

tensor([15.,  9.])

In [24]:
# mean
torch.mean(e)
# mean along col
torch.mean(e, dim=0)

tensor([4., 0., 8.])

In [25]:
# median
torch.median(e)

tensor(0.)

In [26]:
# max and min
torch.max(e)
torch.min(e)

tensor(0.)

In [27]:
# standard deviation
torch.std(e)

tensor(4.4272)

In [28]:
# variance
torch.var(e)

tensor(19.6000)

In [29]:
f = torch.randint(size=(2,3), low=0, high=10)
g = torch.randint(size=(3,2), low=0, high=10)

print(f)
print(g)

tensor([[5, 7, 3],
        [9, 4, 0]])
tensor([[5, 7],
        [5, 9],
        [9, 7]])


In [30]:
# matrix multiplcation
torch.matmul(f, g)

tensor([[ 87, 119],
        [ 65,  99]])

In [31]:
# transpose
torch.transpose(f, 0, 1)

tensor([[5, 9],
        [7, 4],
        [3, 0]])

In [32]:
# determinant
h = torch.randint(size=(3,3), low=0, high=10, dtype=torch.float32)
torch.det(h)

tensor(-110.)

## 5. Comparison operations

In [33]:
i = torch.randint(size=(2,3), low=0, high=10)
j = torch.randint(size=(2,3), low=0, high=10)

print(i)
print(j)

tensor([[7, 8, 3],
        [6, 1, 5]])
tensor([[5, 0, 4],
        [3, 8, 8]])


In [34]:
# greater than
i > j
# less than
i < j
# equal to
i == j
# not equal to
i != j
# greater than equal to

# less than equal to

tensor([[True, True, True],
        [True, True, True]])

## 6. Special functions

In [35]:
k = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
k

tensor([[3., 3., 5.],
        [0., 6., 4.]])

In [36]:
# log
torch.log(k)

tensor([[1.0986, 1.0986, 1.6094],
        [  -inf, 1.7918, 1.3863]])

In [37]:
# exp
torch.exp(k)

tensor([[ 20.0855,  20.0855, 148.4132],
        [  1.0000, 403.4288,  54.5981]])

In [38]:
# sigmoid
torch.sigmoid(k)

tensor([[0.9526, 0.9526, 0.9933],
        [0.5000, 0.9975, 0.9820]])

In [39]:
# softmax
torch.softmax(k, dim=0)

tensor([[0.9526, 0.0474, 0.7311],
        [0.0474, 0.9526, 0.2689]])

In [40]:
# relu
torch.relu(k)

tensor([[3., 3., 5.],
        [0., 6., 4.]])

## Inplace Operations

In [41]:
m = torch.rand(2,3)
n = torch.rand(2,3)

print(m)
print(n)

tensor([[0.6574, 0.3451, 0.0453],
        [0.9798, 0.5548, 0.6868]])
tensor([[0.4920, 0.0748, 0.9605],
        [0.3271, 0.0103, 0.9516]])


In [42]:
m.add_(n)

tensor([[1.1494, 0.4199, 1.0058],
        [1.3069, 0.5650, 1.6384]])

In [43]:
m

tensor([[1.1494, 0.4199, 1.0058],
        [1.3069, 0.5650, 1.6384]])

In [44]:
n

tensor([[0.4920, 0.0748, 0.9605],
        [0.3271, 0.0103, 0.9516]])

In [45]:
torch.relu(m)

tensor([[1.1494, 0.4199, 1.0058],
        [1.3069, 0.5650, 1.6384]])

In [46]:
m.relu_()

tensor([[1.1494, 0.4199, 1.0058],
        [1.3069, 0.5650, 1.6384]])

## Copying a Tensor

In [47]:
a = torch.rand(2,3)
a

tensor([[0.2855, 0.2324, 0.9141],
        [0.7668, 0.1659, 0.4393]])

In [48]:
b = a

In [49]:
b

tensor([[0.2855, 0.2324, 0.9141],
        [0.7668, 0.1659, 0.4393]])

In [50]:
b = a.clone()

In [51]:
b

tensor([[0.2855, 0.2324, 0.9141],
        [0.7668, 0.1659, 0.4393]])

# Creating a simple NN model

In [52]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [53]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [54]:
df.shape

(569, 33)

In [55]:
df.drop(columns = ['id', 'Unnamed: 32'], inplace = True)

In [56]:
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

In [57]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

In [58]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [59]:
X_train

array([[-0.25563736, -0.12670067, -0.22986119, ...,  1.49802801,
         1.71688388,  1.91585093],
       [-0.09693101,  0.39158207, -0.04998881, ...,  0.65991177,
         0.52094814,  1.75953567],
       [-1.26312874, -0.84083218, -1.27329155, ..., -0.9786685 ,
        -0.08211604, -0.1022908 ],
       ...,
       [ 3.00078169,  0.24111289,  3.18941916, ...,  1.75009305,
         0.56511622, -0.19496342],
       [-0.04990691,  0.36053287, -0.06831703, ..., -0.71305497,
        -1.08778927,  0.07468042],
       [ 0.31159087, -0.6688674 ,  0.34982234, ...,  0.45038271,
        -0.5085079 , -0.32336524]])

In [60]:
y_train

47     M
7      M
273    B
554    B
341    B
      ..
476    B
54     M
122    M
544    B
128    B
Name: diagnosis, Length: 455, dtype: object

In [61]:
encoder = LabelEncoder()
y_train  = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [62]:
y_train

array([1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0,
       0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0,
       1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0,
       0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0,
       1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1,
       0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1,
       1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1,

In [87]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Using device:", device)

Using device: cuda


In [88]:
X_train_tensor = torch.from_numpy(X_train).to(device).double()
X_test_tensor = torch.from_numpy(X_test).to(device).double()
y_train_tensor = torch.from_numpy(y_train).to(device).double()
y_test_tensor = torch.from_numpy(y_test).to(device).double()

In [98]:
X_train_tensor.shape

torch.Size([455, 30])

In [109]:
import torch
import torch.nn as nn
class MySimpleNN(nn.Module):
    def __init__(self, num_features):
        super().__init__()
        self.linear = nn.Linear(num_features, 1)
        self.sigmoid = nn.Sigmoid()   
    def forward(self, features):
        out = self.linear(features)
        out = self.sigmoid(out)
        return out



In [113]:
learning_rate = 0.01
epochs = 21
model = MySimpleNN(X_train_tensor.shape[1]).to(device).double()
loss_function = nn.BCELoss()
optimizer = torch.optim.SGD(model.parameters(), lr = learning_rate)

In [114]:
for epoch in range(epochs):
    y_pred = model.forward(X_train_tensor)
    loss = loss_function(y_pred, y_train_tensor.view(-1,1))
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()
    print(f"Epoch: {epoch+1}, Loss: {loss.item()}")

Epoch: 1, Loss: 0.9278670211035088
Epoch: 2, Loss: 0.8975905766016031
Epoch: 3, Loss: 0.8688944348748057
Epoch: 4, Loss: 0.8417374980640211
Epoch: 5, Loss: 0.8160717754424892
Epoch: 6, Loss: 0.7918432172174151
Epoch: 7, Loss: 0.7689926717397412
Epoch: 8, Loss: 0.747456920190532
Epoch: 9, Loss: 0.727169745497697
Epoch: 10, Loss: 0.7080629994305457
Epoch: 11, Loss: 0.690067640263906
Epoch: 12, Loss: 0.6731147190691283
Epoch: 13, Loss: 0.6571362935281958
Epoch: 14, Loss: 0.6420662457565599
Epoch: 15, Loss: 0.6278409791282462
Epoch: 16, Loss: 0.6143999723519905
Epoch: 17, Loss: 0.6016861780625469
Epoch: 18, Loss: 0.5896462658450891
Epoch: 19, Loss: 0.5782307222563629
Epoch: 20, Loss: 0.5673938299047863
Epoch: 21, Loss: 0.5570935525338545


In [115]:
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred = (y_pred > 1).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')

Accuracy: 0.5701754093170166


## creating NN fully by PyTorch

In [71]:
# create model class
import torch
import torch.nn as nn

class Model(nn.Module):

  def __init__(self, num_features):

    super().__init__()
    self.network = nn.Sequential(
        nn.Linear(num_features, 3),
        nn.ReLU(),
        nn.Linear(3, 1),
        nn.Sigmoid()
    )

  def forward(self, features):

    out = self.network(features)

    return out

In [72]:
# create dataset
features = torch.rand(10,5)
# create model
model = Model(features.shape[1])
# call model for forward pass
# model.forward(features)
model(features)

tensor([[0.5420],
        [0.5420],
        [0.5420],
        [0.5420],
        [0.5420],
        [0.5420],
        [0.5547],
        [0.5424],
        [0.5433],
        [0.5521]], grad_fn=<SigmoidBackward0>)

In [74]:
from torchinfo import summary
summary(model, input_size=(10, 5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Sequential: 1-1                        [10, 1]                   --
│    └─Linear: 2-1                       [10, 3]                   18
│    └─ReLU: 2-2                         [10, 3]                   --
│    └─Linear: 2-3                       [10, 1]                   4
│    └─Sigmoid: 2-4                      [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

## Dataset And Dataloder

In [116]:
from sklearn.datasets import make_classification

In [117]:
X, y = make_classification(
    n_samples=10,       # Number of samples
    n_features=2,       # Number of features
    n_informative=2,    # Number of informative features
    n_redundant=0,      # Number of redundant features
    n_classes=2,        # Number of classes
    random_state=42     # For reproducibility
)

In [118]:
X

array([[ 1.06833894, -0.97007347],
       [-1.14021544, -0.83879234],
       [-2.8953973 ,  1.97686236],
       [-0.72063436, -0.96059253],
       [-1.96287438, -0.99225135],
       [-0.9382051 , -0.54304815],
       [ 1.72725924, -1.18582677],
       [ 1.77736657,  1.51157598],
       [ 1.89969252,  0.83444483],
       [-0.58723065, -1.97171753]])

In [119]:
X.shape

(10, 2)

In [120]:
y

array([1, 0, 0, 0, 0, 1, 1, 1, 1, 0])

In [121]:
X = torch.tensor(X, dtype=torch.float32)
y = torch.tensor(y, dtype=torch.long)

In [122]:
X

tensor([[ 1.0683, -0.9701],
        [-1.1402, -0.8388],
        [-2.8954,  1.9769],
        [-0.7206, -0.9606],
        [-1.9629, -0.9923],
        [-0.9382, -0.5430],
        [ 1.7273, -1.1858],
        [ 1.7774,  1.5116],
        [ 1.8997,  0.8344],
        [-0.5872, -1.9717]])

In [124]:
from torch.utils.data import Dataset, DataLoader

In [136]:
class CustomDataset(Dataset):
    def __init__(self, features, labels):
        self.features = features
        self.labels = labels
    def __len__(self):
        return self.features.shape[0]
    def __getitem__(self, index):
        return self.features[index], self.labels[index]

In [137]:
dataset = CustomDataset(X,y)

In [138]:
len(dataset)

10

In [140]:
dataloader = DataLoader(dataset, batch_size = 2, shuffle = True)

In [145]:
for batch_features , batch_labels in dataloader:
    print(batch_features)
    print(batch_labels)
    print("_"*50)

tensor([[-2.8954,  1.9769],
        [ 1.0683, -0.9701]])
tensor([0, 1])
----------------------------------------------------------------------------------------------------
tensor([[-0.5872, -1.9717],
        [ 1.8997,  0.8344]])
tensor([0, 1])
----------------------------------------------------------------------------------------------------
tensor([[ 1.7774,  1.5116],
        [-1.1402, -0.8388]])
tensor([1, 0])
----------------------------------------------------------------------------------------------------
tensor([[-1.9629, -0.9923],
        [-0.9382, -0.5430]])
tensor([0, 1])
----------------------------------------------------------------------------------------------------
tensor([[-0.7206, -0.9606],
        [ 1.7273, -1.1858]])
tensor([0, 1])
----------------------------------------------------------------------------------------------------
